- hosts: localhost
  roles:
    - Azure.azure_preview_modules
  tasks:
    - name: Create sample container instance
      azure_rm_containerinstance:
        resource_group: zims-rg1
        name: mycontainerabcxyz
        os_type: linux
        ip_address: public
        location: eastus
        ports:
          - 80
        containers:
          - name: mycontainer1
            image: httpd
            memory: 1.5
            ports:
              - 80
      register: output
    - name: Dump IP Address
      debug:
        msg: IP Address is {{ output.state.ip_address.ip }}

