./ansible-pr.sh azure_rm_sqlserver_facts
./ansible-pr.sh azure_rm_mysqlserver_facts
./ansible-pr.sh azure_rm_postgresqlserver_facts
./ansible-pr.sh azure_rm_sqldatabase
./ansible-pr.sh azure_rm_mysqldatabase
./ansible-pr.sh azure_rm_postgresqldatabase
./ansible-pr.sh azure_rm_sqldatabase_facts
./ansible-pr.sh azure_rm_mysqldatabase_facts
./ansible-pr.sh azure_rm_postgresqldatabase_facts
./ansible-pr.sh azure_rm_sqlfirewallrule
./ansible-pr.sh azure_rm_mysqlfirewallrule
./ansible-pr.sh azure_rm_postgresqlfirewallrule
./ansible-pr.sh azure_rm_sqlfirewallrule_facts
./ansible-pr.sh azure_rm_mysqlfirewallrule_facts
./ansible-pr.sh azure_rm_postgresqlfirewallrule_facts
